# Generated by Django 6.0.2 on 2026-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('Production', 'Production'), ('Warehouse', 'Warehouse'), ('Viewer', 'Viewer')], default='Viewer', max_length=50),
        ),
    ]
