# Generated by Django 6.0.2 on 2026-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('QA Head', 'QA Head (HOD)'), ('QA Manager', 'QA Manager'), ('QA Executive', 'QA Executive'), ('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('Production', 'Production'), ('Warehouse', 'Warehouse'), ('Viewer', 'Viewer')], default='Viewer', max_length=50),
        ),
    ]
