# Generated by Django 6.0.2 on 2026-06-19 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password_hash', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('meaning', models.TextField(default='', help_text='Meaning of the signature (e.g. "I approve this CAPA closure")')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esignatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
