# Generated by Django 6.0.1 on 2026-02-04 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deviation_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QA_REVIEW', 'QA Review'), ('INVESTIGATION', 'Investigation'), ('CAPA_REQUIRED', 'CAPA Required'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('occurrence_date', models.DateField()),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_deviations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
