# Generated by Django 6.0.2 on 2026-02-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capa_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action'), ('PREVENTIVE', 'Preventive Action')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('PENDING', 'Pending Implementation'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified (Closed)')], default='PLANNING', max_length=20)),
                ('due_date', models.DateField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='quality.deviation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
