# Generated by Django 6.0.2 on 2026-02-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_capa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cc_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('justification', models.TextField(help_text='Why is this change necessary?')),
                ('change_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('EMERGENCY', 'Emergency')], default='PERMANENT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('EVALUATION', 'Impact Evaluation'), ('APPROVAL', 'Pending Approval'), ('IMPLEMENTATION', 'Implementation'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls', to='quality.capa')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
