# Generated by Django 6.0.2 on 2026-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_changecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changecontrol',
            name='change_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('EMERGENCY', 'Emergency')], default='STANDARD', max_length=20),
        ),
    ]
