# Generated by Django 6.0.2 on 2026-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_alter_changecontrol_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='department',
            field=models.CharField(default='QA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
