# Generated by Django 6.0.2 on 2026-02-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_capa_department_changecontrol_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quality.capa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
