# Generated by Django 6.0.2 on 2026-02-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_capa_action_plan_capa_root_cause_capaaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='immediate_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviation',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('PENDING', 'Pending Implementation'), ('IMPLEMENTATION', 'Implementation'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified (Closed)')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviation',
            name='deviation_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deviation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INVESTIGATION', 'Investigation'), ('QA_REVIEW', 'QA Review'), ('UNDER_REVIEW', 'Under Review'), ('CAPA_REQUIRED', 'CAPA Required'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
    ]
