# Generated by Django 6.0.2 on 2026-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_deviation_immediate_actions_deviation_root_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecontrol',
            name='impact_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='risk_level',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
