# Generated by Django 6.0.2 on 2026-06-19 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '__first__'),
        ('quality', '0008_changecontrol_impact_data_changecontrol_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivenessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.TextField(help_text='What defines a successful CAPA?')),
                ('due_date', models.DateField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='effectiveness/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('capa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_check', to='quality.capa')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='effectiveness_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OOSInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oos_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('product', models.CharField(max_length=200)),
                ('batch_lot', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=200)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('result_obtained', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('phase1', 'Phase 1 — Lab Investigation'), ('phase2', 'Phase 2 — Full Investigation'), ('invalidated', 'Invalidated'), ('confirmed_oos', 'Confirmed OOS')], default='phase1', max_length=20)),
                ('assignable_cause', models.BooleanField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_oos', to=settings.AUTH_USER_MODEL)),
                ('linked_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oos_investigations', to='quality.capa')),
                ('linked_test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oos_investigations', to='laboratory.testresult')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_oos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OOSPhase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument_check', models.BooleanField(default=False, help_text='Instrument calibration verified?')),
                ('analyst_retest_result', models.CharField(blank=True, max_length=100)),
                ('calculation_error_found', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('conclusion', models.CharField(blank=True, choices=[('assignable_cause_found', 'Assignable Cause Found — Invalidate'), ('proceed_to_phase2', 'No Assignable Cause — Proceed to Phase 2')], max_length=30)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phase1', to='quality.oosinvestigation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OOSPhase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resampling_conducted', models.BooleanField(default=False)),
                ('additional_results', models.JSONField(default=list)),
                ('conclusion', models.CharField(blank=True, choices=[('confirmed_oos', 'Confirmed OOS'), ('invalidated', 'Result Invalidated')], max_length=20)),
                ('qa_review_notes', models.TextField(blank=True)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phase2', to='quality.oosinvestigation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OOTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('three_sigma', '3-Sigma Rule'), ('custom_range', 'Custom Range')], default='three_sigma', max_length=20)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('product', 'test_name')},
            },
        ),
    ]
