# Generated by Django 6.0.2 on 2026-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_effectivenesscheck_oosinvestigation_oosphase1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('PENDING', 'Pending Implementation'), ('IMPLEMENTATION', 'Implementation'), ('COMPLETED', 'Completed'), ('EFFECTIVENESS_PENDING', 'Effectiveness Pending'), ('VERIFIED', 'Verified (Closed)')], default='PLANNING', max_length=30),
        ),
    ]
