version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: qms_db_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qms_db
      - POSTGRES_USER=qms_user
      - POSTGRES_PASSWORD=qms_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: qms_redis
    restart: always
    ports:
      - "5379:6379"

volumes:
  postgres_data:
