# Generated by Django 6.0.2 on 2026-06-19 08:42

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0009_effectivenesscheck_oosinvestigation_oosphase1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComplaint',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('complaint_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('complainant_type', models.CharField(choices=[('customer', 'Customer / Patient'), ('hcp', 'Healthcare Professional'), ('distributor', 'Distributor'), ('regulator', 'Regulatory Authority'), ('internal', 'Internal')], max_length=20)),
                ('product', models.CharField(max_length=200)),
                ('batch_lot', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=20)),
                ('regulatory_reportable', models.BooleanField(default=False)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_investigation', 'In Investigation'), ('pending_closure', 'Pending Closure'), ('closed', 'Closed')], default='new', max_length=30)),
                ('mdr_submission_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical complaint',
                'verbose_name_plural': 'historical complaints',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvestigation',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('findings', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical investigation',
                'verbose_name_plural': 'historical investigations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMDRReport',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('report_number', models.CharField(blank=True, max_length=50)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('regulatory_body', models.CharField(default='FDA', max_length=100)),
                ('submission_notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical mdr report',
                'verbose_name_plural': 'historical mdr reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('findings', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MDRReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('report_number', models.CharField(blank=True, max_length=50)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('regulatory_body', models.CharField(default='FDA', max_length=100)),
                ('submission_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('complaint_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('complainant_type', models.CharField(choices=[('customer', 'Customer / Patient'), ('hcp', 'Healthcare Professional'), ('distributor', 'Distributor'), ('regulator', 'Regulatory Authority'), ('internal', 'Internal')], max_length=20)),
                ('product', models.CharField(max_length=200)),
                ('batch_lot', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=20)),
                ('regulatory_reportable', models.BooleanField(default=False)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_investigation', 'In Investigation'), ('pending_closure', 'Pending Closure'), ('closed', 'Closed')], default='new', max_length=30)),
                ('mdr_submission_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='quality.capa')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
