# Generated by Django 6.0.2 on 2026-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='quiz_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
