import { type PermissionMatrix } from "../services/permission.service";

export const ROLE_PERMISSIONS: PermissionMatrix = {
  Admin: {
    dashboard: ["view", "export"],
    dms: ["view", "create", "edit", "delete", "approve"],
    training: ["view", "create", "edit", "delete"],
    training_matrix: ["view", "export"],
    deviations: ["view", "create", "edit", "delete", "approve", "close", "reopen"],
    capa: ["view", "create", "edit", "delete", "approve", "close"],
    change: ["view", "create", "edit", "delete", "approve", "close"],
    settings: ["view", "edit"],
    reports: ["view", "export"],
    audits: ["view", "create", "edit", "delete", "approve", "close"],
    complaints: ["view", "create", "edit", "delete", "approve", "close"],
    risks: ["view", "create", "edit", "delete", "approve", "close"],
    suppliers: ["view", "create", "edit", "delete", "approve"],
    nonconformance: ["view", "create", "edit", "delete", "approve", "close"],
    oos: ["view", "create", "edit", "approve", "close"],
    laboratory: ["view", "create", "edit", "approve"],
    batch_records: ["view", "create", "edit", "approve", "close"],
    knowledge: ["view", "create", "edit", "delete"],
  },

  "QA Head": {
    dashboard: ["view", "export"],
    dms: ["view", "create", "edit", "approve"],
    training: ["view", "create", "edit"],
    training_matrix: ["view", "export"],
    deviations: ["view", "create", "edit", "approve", "close"],
    capa: ["view", "create", "edit", "approve", "close"],
    change: ["view", "create", "edit", "approve", "close"],
    settings: ["view"],
    reports: ["view", "export"],
    audits: ["view", "create", "edit", "approve", "close"],
    complaints: ["view", "create", "edit", "approve", "close"],
    risks: ["view", "create", "edit", "approve", "close"],
    suppliers: ["view", "create", "edit", "approve"],
    nonconformance: ["view", "create", "edit", "approve", "close"],
    oos: ["view", "create", "edit", "approve", "close"],
    laboratory: ["view", "create", "edit", "approve"],
    batch_records: ["view", "create", "edit", "approve", "close"],
    knowledge: ["view", "create", "edit"],
  },

  "QA Manager": {
    dashboard: ["view", "export"],
    dms: ["view", "create", "edit", "approve"],
    training: ["view", "create", "edit"],
    training_matrix: ["view"],
    deviations: ["view", "create", "edit", "approve"],
    capa: ["view", "create", "edit", "approve"],
    change: ["view", "create", "edit", "approve"],
    settings: ["view"],
    reports: ["view", "export"],
    audits: ["view", "create", "edit", "approve"],
    complaints: ["view", "create", "edit", "approve"],
    risks: ["view", "create", "edit", "approve"],
    suppliers: ["view", "create", "edit", "approve"],
    nonconformance: ["view", "create", "edit", "approve"],
    oos: ["view", "create", "edit", "approve"],
    laboratory: ["view", "create", "edit"],
    batch_records: ["view", "create", "edit", "approve"],
    knowledge: ["view", "create", "edit"],
  },

  "QA Executive": {
    dashboard: ["view"],
    dms: ["view", "create", "edit"],
    training: ["view", "create"],
    training_matrix: ["view"],
    deviations: ["view", "create", "edit"],
    capa: ["view", "create", "edit"],
    change: ["view", "create", "edit"],
    settings: ["view"],
    reports: ["view"],
    audits: ["view", "create", "edit"],
    complaints: ["view", "create", "edit"],
    risks: ["view", "create", "edit"],
    suppliers: ["view", "create"],
    nonconformance: ["view", "create", "edit"],
    oos: ["view", "create", "edit"],
    laboratory: ["view", "create"],
    batch_records: ["view", "create"],
    knowledge: ["view", "create"],
  },

  QA: {
    dashboard: ["view", "export"],
    dms: ["view", "create", "edit", "approve"],
    training: ["view", "create", "edit"],
    training_matrix: ["view"],
    deviations: ["view", "create", "edit", "approve", "close"],
    capa: ["view", "create", "edit", "approve", "close"],
    change: ["view", "create", "edit", "approve", "close"],
    settings: ["view"],
    reports: ["view", "export"],
    audits: ["view", "create", "edit", "approve"],
    complaints: ["view", "create", "edit", "approve"],
    risks: ["view", "create", "edit", "approve"],
    suppliers: ["view", "create", "edit"],
    nonconformance: ["view", "create", "edit", "approve"],
    oos: ["view", "create", "edit", "approve"],
    laboratory: ["view", "create", "edit"],
    batch_records: ["view", "create", "edit"],
    knowledge: ["view", "create"],
  },

  QC: {
    dashboard: ["view"],
    dms: ["view", "create"],
    training: ["view"],
    training_matrix: ["view"],
    deviations: ["view", "create"],
    capa: ["view", "create"],
    change: ["view"],
    settings: ["view"],
    reports: ["view"],
    audits: ["view"],
    complaints: ["view", "create"],
    risks: ["view"],
    suppliers: ["view"],
    nonconformance: ["view", "create"],
    oos: ["view", "create", "edit"],
    laboratory: ["view", "create", "edit"],
    batch_records: ["view"],
    knowledge: ["view"],
  },

  Production: {
    dashboard: ["view"],
    dms: ["view"],
    training: ["view"],
    training_matrix: ["view"],
    deviations: ["view", "create"],
    capa: ["view"],
    change: ["view"],
    settings: [],
    reports: [],
    audits: ["view"],
    complaints: ["view"],
    risks: ["view"],
    suppliers: ["view"],
    nonconformance: ["view", "create"],
    oos: ["view"],
    laboratory: ["view"],
    batch_records: ["view", "create", "edit"],
    knowledge: ["view"],
  },

  Warehouse: {
    dashboard: ["view"],
    dms: ["view"],
    training: ["view"],
    training_matrix: ["view"],
    deviations: ["view", "create"],
    capa: ["view"],
    change: ["view"],
    settings: [],
    reports: [],
    audits: ["view"],
    complaints: ["view", "create"],
    risks: ["view"],
    suppliers: ["view"],
    nonconformance: ["view", "create"],
    oos: ["view"],
    laboratory: ["view"],
    batch_records: ["view"],
    knowledge: ["view"],
  },

  Viewer: {
    dashboard: ["view"],
    dms: ["view"],
    training: ["view"],
    training_matrix: ["view"],
    deviations: ["view"],
    capa: ["view"],
    change: ["view"],
    settings: [],
    reports: [],
    audits: ["view"],
    complaints: ["view"],
    risks: ["view"],
    suppliers: ["view"],
    nonconformance: ["view"],
    oos: ["view"],
    laboratory: ["view"],
    batch_records: ["view"],
    knowledge: ["view"],
  },
};
