# Generated by Django 6.0.2 on 2026-06-19 08:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_site_alter_user_role'),
        ('quality', '0009_effectivenesscheck_oosinvestigation_oosphase1_and_more'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProductionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('manufacture_date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('released', 'Released')], default='issued', max_length=20)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'ordering': ['-manufacture_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('bpr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='batch_records.batchproductionrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('esignature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.esignature')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_releases', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMasterBatchRecord',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('theoretical_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('yield_formula', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.site')),
            ],
            options={
                'verbose_name': 'historical master batch record',
                'verbose_name_plural': 'historical master batch records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MasterBatchRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('theoretical_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('yield_formula', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalBatchProductionRecord',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(db_index=True, max_length=50)),
                ('manufacture_date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('released', 'Released')], default='issued', max_length=20)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.site')),
                ('mbr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='batch_records.masterbatchrecord')),
            ],
            options={
                'verbose_name': 'historical batch production record',
                'verbose_name_plural': 'historical batch production records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='batchproductionrecord',
            name='mbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_records', to='batch_records.masterbatchrecord'),
        ),
        migrations.CreateModel(
            name='MBRStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_critical', models.BooleanField(default=False)),
                ('esig_required', models.BooleanField(default=False)),
                ('expected_range', models.CharField(blank=True, help_text='e.g. 98.0–102.0%', max_length=200)),
                ('mbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='batch_records.masterbatchrecord')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('mbr', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='BPRStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=200)),
                ('bpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='batch_records.batchproductionrecord')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
                ('deviation_linked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpr_steps', to='quality.deviation')),
                ('esignature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shared.esignature')),
                ('mbr_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpr_executions', to='batch_records.mbrstep')),
            ],
        ),
    ]
