# Generated by Django 6.0.2 on 2026-06-19 11:20

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_site_alter_user_role'),
        ('batch_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIPQCCheck',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=100)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pass_fail', models.CharField(blank=True, max_length=10)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bpr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='batch_records.batchproductionrecord')),
                ('checked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.site')),
            ],
            options={
                'verbose_name': 'historical ipqc check',
                'verbose_name_plural': 'historical ipqc checks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IPQCCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=100)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pass_fail', models.CharField(blank=True, max_length=10)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('bpr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_checks', to='batch_records.batchproductionrecord')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipqc_checks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
