# Generated by Django 6.0.2 on 2026-06-19 08:42

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_site_alter_user_role'),
        ('quality', '0009_effectivenesscheck_oosinvestigation_oosphase1_and_more'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('decision', models.CharField(choices=[('use_as_is', 'Use As-Is'), ('rework', 'Rework'), ('reject', 'Reject'), ('rtv', 'Return to Vendor')], max_length=20)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('justification', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to=settings.AUTH_USER_MODEL)),
                ('esignature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.esignature')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalNCReport',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nc_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('product', models.CharField(max_length=200)),
                ('batch_lot', models.CharField(max_length=100)),
                ('quantity_affected', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('defect_description', models.TextField()),
                ('defect_category', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=20)),
                ('hold_status', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dispositioned', 'Dispositioned'), ('closed', 'Closed')], default='open', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nonconformance.disposition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_capa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quality.capa')),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.site')),
            ],
            options={
                'verbose_name': 'historical nc report',
                'verbose_name_plural': 'historical nc reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NCReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nc_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('product', models.CharField(max_length=200)),
                ('batch_lot', models.CharField(max_length=100)),
                ('quantity_affected', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('defect_description', models.TextField()),
                ('defect_category', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=20)),
                ('hold_status', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dispositioned', 'Dispositioned'), ('closed', 'Closed')], default='open', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nonconformance.disposition')),
                ('linked_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformances', to='quality.capa')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='nonconformance.ncreport')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDisposition',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('decision', models.CharField(choices=[('use_as_is', 'Use As-Is'), ('rework', 'Rework'), ('reject', 'Reject'), ('rtv', 'Return to Vendor')], max_length=20)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('justification', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('esignature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.esignature')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.site')),
                ('nc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nonconformance.ncreport')),
            ],
            options={
                'verbose_name': 'historical disposition',
                'verbose_name_plural': 'historical dispositions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='disposition',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='nonconformance.ncreport'),
        ),
    ]
