import io
from django.http import HttpResponse
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import generics

from .models import APQRReport
from .serializers import APQRReportSerializer


def generate_management_review_pdf(data: dict, generated_by, period: str) -> io.BytesIO:
    """
    Render the JSON returned by ManagementReviewView.get() into a PDF.

    `data` has the shape {'kpis': {open_capas: N, overdue_complaints: N, ...}} —
    the KPI table is built from data['kpis'], not from top-level scalar keys.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20 * mm, leftMargin=20 * mm,
        topMargin=25 * mm, bottomMargin=25 * mm,
    )
    styles = getSampleStyleSheet()
    elements = []

    # ── Header ────────────────────────────────────────────────────────────
    elements.append(Paragraph(
        'Quality Management Review Report',
        ParagraphStyle('Title', fontSize=14, fontName='Helvetica-Bold',
                        alignment=1, textColor=colors.HexColor('#1a3a5c'), spaceAfter=2)
    ))
    elements.append(Paragraph(
        f'NexGen Pharma QMS  |  Period: {period}',
        ParagraphStyle('Sub', fontSize=10, alignment=1, spaceAfter=4)
    ))
    elements.append(Paragraph(
        f'Generated by: {generated_by.get_full_name()} '
        f'({generated_by.email})  |  {timezone.now().strftime("%Y-%m-%d %H:%M UTC")}',
        ParagraphStyle('Meta', fontSize=8, alignment=1,
                        textColor=colors.HexColor('#666666'), spaceAfter=4)
    ))
    elements.append(HRFlowable(width='100%', thickness=1.5, color=colors.HexColor('#1a3a5c')))
    elements.append(Spacer(1, 5 * mm))

    # ── KPI summary table ─────────────────────────────────────────────────
    elements.append(Paragraph(
        'Quality KPI Summary',
        ParagraphStyle('SHead', fontSize=11, fontName='Helvetica-Bold',
                        textColor=colors.HexColor('#1a3a5c'), spaceAfter=3)
    ))

    kpis = data.get('kpis', {})
    kpi_rows = [['Metric', 'Value', 'Status']]
    for key, value in kpis.items():
        label = key.replace('_', ' ').title()
        status = 'OK' if value == 0 else 'Review'
        kpi_rows.append([label, str(value), status])

    kpi_table = Table(kpi_rows, colWidths=[90 * mm, 40 * mm, 30 * mm], repeatRows=1)
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a3a5c')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f7fa')]),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#cccccc')),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 5 * mm))

    # ── Footer ────────────────────────────────────────────────────────────
    elements.append(HRFlowable(width='100%', thickness=0.5, color=colors.grey))
    elements.append(Spacer(1, 2 * mm))
    elements.append(Paragraph(
        'This report is generated by NexGen QMS and is subject to ICH Q10 '
        'management review requirements. Retain per site document retention SOP.',
        ParagraphStyle('Footer', fontSize=6.5, fontName='Helvetica-Oblique',
                        textColor=colors.HexColor('#666666'))
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_apqr_pdf(report: APQRReport) -> io.BytesIO:
    """Render an APQRReport's saved `content` JSON into a PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=22 * mm, leftMargin=22 * mm,
        topMargin=25 * mm, bottomMargin=25 * mm,
    )
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Spacer(1, 20 * mm))
    elements.append(Paragraph(
        'Annual Product Quality Review',
        ParagraphStyle('CoverTitle', fontSize=20, fontName='Helvetica-Bold', alignment=1,
                        textColor=colors.HexColor('#1a3a5c'), spaceAfter=8)
    ))
    elements.append(HRFlowable(width='100%', thickness=2, color=colors.HexColor('#1a3a5c')))
    elements.append(Spacer(1, 8 * mm))

    cover_rows = [
        ['Product', report.product or '-'],
        ['Period', f"{report.period_start} to {report.period_end}"],
        ['Status', report.status.upper()],
        ['Generated', str(report.generated_at)],
    ]
    cover_table = Table(cover_rows, colWidths=[50 * mm, 120 * mm])
    cover_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#eef2f7')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(cover_table)
    elements.append(PageBreak())

    content = report.content or {}
    # Matches the keys actually written by APQRGenerateView: product_summary, deviations,
    # capas, oos, complaints, recommendations.
    SECTION_ORDER = [
        ('product_summary', '1. Product Summary'),
        ('deviations', '2. Deviations'),
        ('capas', '3. CAPAs'),
        ('oos', '4. Out-of-Specification Investigations'),
        ('complaints', '5. Complaints'),
        ('recommendations', '6. Recommendations'),
    ]

    for key, title in SECTION_ORDER:
        if key not in content:
            continue

        elements.append(Paragraph(
            title,
            ParagraphStyle('SectionHead', fontSize=12, fontName='Helvetica-Bold',
                            textColor=colors.HexColor('#1a3a5c'), spaceAfter=4, spaceBefore=6)
        ))
        elements.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#aaaaaa')))
        elements.append(Spacer(1, 3 * mm))

        section_val = content[key]
        if isinstance(section_val, str):
            elements.append(Paragraph(section_val, styles['Normal']))
        elif isinstance(section_val, dict):
            table_data = [[str(k), str(v)] for k, v in section_val.items()]
            if table_data:
                t = Table(table_data, colWidths=[60 * mm, 110 * mm])
                t.setStyle(TableStyle([
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
                    ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f5f7fa')),
                ]))
                elements.append(t)
        elif isinstance(section_val, list):
            for item in section_val:
                elements.append(Paragraph(
                    f"• {item}",
                    ParagraphStyle('Rec', fontSize=9, fontName='Helvetica', leftIndent=6,
                                    backColor=colors.HexColor('#e8f4fd'), borderPadding=3, spaceBefore=2)
                ))

        elements.append(Spacer(1, 4 * mm))

    if report.approved_by:
        elements.append(PageBreak())
        elements.append(Paragraph('Approval Record', styles['Heading2']))
        approval_data = [
            ['Approved By', report.approved_by.get_full_name() or report.approved_by.username],
            ['Role', getattr(report.approved_by, 'role', '-')],
        ]
        approval_table = Table(approval_data, colWidths=[55 * mm, 120 * mm])
        approval_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#eef2f7')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        elements.append(approval_table)

    elements.append(Spacer(1, 6 * mm))
    elements.append(Paragraph(
        'This Annual Product Quality Review was generated by NexGen QMS and is subject to '
        '21 CFR Part 11 and ICH Q10 controls. This document must be retained per site SOP.',
        ParagraphStyle('Footer', fontSize=6.5, fontName='Helvetica-Oblique', textColor=colors.HexColor('#666666'))
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer


class ManagementReviewView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        from quality.models import Capa, Deviation, OOSInvestigation
        from complaints.models import Complaint
        from audits.models import Finding
        from suppliers.models import Supplier
        from nonconformance.models import NCReport
        from datetime import date, timedelta

        today = date.today()

        data = {
            'kpis': {
                'open_capas': Capa.objects.filter(status__in=['PLANNING', 'PENDING', 'IMPLEMENTATION']).count(),
                'overdue_complaints': Complaint.objects.filter(
                    is_active=True, response_deadline__lt=today
                ).exclude(status='closed').count(),
                'open_oos': OOSInvestigation.objects.filter(phase__in=['phase1', 'phase2']).count(),
                'open_findings': Finding.objects.filter(status='open', is_active=True).count(),
                'expiring_suppliers': Supplier.objects.filter(
                    is_active=True,
                    status='qualified',
                    expiry_date__lte=today + timedelta(days=30),
                ).count(),
                'open_ncs': NCReport.objects.filter(status='open', is_active=True).count(),
            }
        }

        if request.query_params.get('format') == 'pdf':
            period = request.query_params.get('period', str(timezone.now().year))
            buf = generate_management_review_pdf(data, request.user, period)
            response = HttpResponse(buf.read(), content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="management-review-{period}.pdf"'
            return response

        return Response(data)


class APQRGenerateView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        product = request.data.get('product')
        year = request.data.get('year')

        if not product or not year:
            return Response({'error': 'product and year are required'}, status=400)

        role = getattr(request.user, 'role', '')
        if role not in ('Admin', 'QA Head', 'QA Manager'):
            return Response({'error': 'Insufficient permissions'}, status=403)

        from datetime import date
        period_start = date(int(year), 1, 1)
        period_end = date(int(year), 12, 31)

        # Aggregate data from all modules
        from quality.models import Deviation, Capa, OOSInvestigation
        from complaints.models import Complaint
        from nonconformance.models import NCReport

        content = {
            'product_summary': f'Annual Product Quality Review for {product} — Year {year}',
            'deviations': {
                'total': Deviation.objects.filter(
                    created_at__year=int(year),
                    department__icontains=product,
                ).count(),
            },
            'capas': {
                'total': Capa.objects.filter(created_at__year=int(year)).count(),
                'closed': Capa.objects.filter(created_at__year=int(year), status='VERIFIED').count(),
            },
            'oos': {
                'total': OOSInvestigation.objects.filter(
                    created_at__year=int(year), product__icontains=product
                ).count(),
            },
            'complaints': {
                'total': Complaint.objects.filter(
                    received_date__year=int(year), product__icontains=product, is_active=True
                ).count(),
            },
            'recommendations': [
                'Review and update training matrix for all production personnel.',
                'Ensure all CAPA effectiveness checks are completed within due dates.',
                'Verify supplier qualification expiry dates and initiate re-qualification as needed.',
            ],
        }

        report = APQRReport.objects.create(
            product=product,
            period_start=period_start,
            period_end=period_end,
            content=content,
            created_by=request.user,
            modified_by=request.user,
        )

        return Response(APQRReportSerializer(report).data, status=201)


class APQRDetailView(generics.RetrieveAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = APQRReportSerializer
    queryset = APQRReport.objects.all()


class APQRExportView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, pk=None):
        try:
            report = APQRReport.objects.get(pk=pk)
        except APQRReport.DoesNotExist:
            return Response({'error': 'APQR report not found.'}, status=404)

        if not report.content:
            return Response({'error': 'APQR content not yet generated. Run generate first.'}, status=400)

        buf = generate_apqr_pdf(report)
        response = HttpResponse(buf.read(), content_type='application/pdf')
        response['Content-Disposition'] = (
            f'attachment; filename="APQR-{report.product}-{report.period_start}.pdf"'
        )
        return response
