# Generated by Django 6.0.2 on 2026-02-04 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('doc_type', models.CharField(choices=[('SOP', 'Standard Operating Procedure'), ('POL', 'Policy'), ('WI', 'Work Instruction'), ('FORM', 'Form')], default='SOP', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('EFFECTIVE', 'Effective'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('change_log', models.TextField(help_text='Reason for change')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dms.document')),
            ],
            options={
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
