# Generated by Django 6.0.2 on 2026-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
